выполнение дз по TestNg
itreyser/SauceDemo_QA26_Vasilevskiy pull request #3
Opened 2024-06-15 20:36 UTC by itreyser

2024-06-16 19:37 UTC, voropa requested changes

2024-06-16 19:37 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +        driver.get("https://www.saucedemo.com/inventory.html");
why do you need to navigate to this url before logout?

2024-06-16 19:37 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +        productsPage.logOut();
Why do you logout in this test?

It makes sense to create a separate test for logout

2024-06-16 21:31 UTC, itreyser commented on src/test/java/pages/ProductsPage.java
> +        driver.get("https://www.saucedemo.com/inventory.html");
это я экспериментировал и забыл убрать

2024-06-16 21:33 UTC, itreyser commented on src/test/java/tests/LoginTest.java
> +        productsPage.logOut();
Это был тестовый метод, который я забыл удалить. Я создал отдельный AfterMethod который удаляет куки и делает рефреш после каждого теста.

2024-06-17 08:53 UTC, voropa approved these changes

2024-06-17 08:54 UTC, merged